SELECT D.PRODUCT_CODE
     , SUM(D.PRICE * S.SALES_AMOUNT) AS SALES
FROM PRODUCT D, OFFLINE_SALE S
WHERE D.PRODUCT_ID = S.PRODUCT_ID
GROUP BY D.PRODUCT_CODE
ORDER BY SALES DESC, D.PRODUCT_CODE ASC;