SELECT TO_CHAR(B.SALES_DATE, 'yyyy') AS YEAR
     , TO_NUMBER(TO_CHAR(B.SALES_DATE, 'MM')) AS MONTH
     , COUNT(DISTINCT B.USER_ID) AS PUCHASED_USERS
     , ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(USER_ID)
                               FROM USER_INFO
                               WHERE TO_CHAR(JOINED, 'yyyy') = '2021' ), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE B LEFT JOIN USER_INFO A
ON B.USER_ID = A.USER_ID
WHERE TO_CHAR(A.JOINED, 'yyyy') = '2021'
GROUP BY TO_CHAR(B.SALES_DATE,'yyyy'),TO_NUMBER(TO_CHAR(B.SALES_DATE,'MM'))
ORDER BY YEAR, MONTH;


