SELECT MEMBER_NAME, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD')
FROM
(
    SELECT MEMBER_ID, MEMBER_NAME
    FROM MEMBER_PROFILE
) A

JOIN

(
SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
FROM REST_REVIEW
WHERE MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(MEMBER_ID) = (
            SELECT MAX(CNT) AS MAX_CNT
            FROM
            (
                SELECT MEMBER_ID, COUNT(MEMBER_ID) as CNT
                FROM REST_REVIEW
                GROUP BY MEMBER_ID
            )
        )
    ) 
) B

ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;