SELECT YEAR, TO_NUMBER(MONTH) AS MONTH, PUCHASED_USERS, ROUND(PUCHASED_USERS/COUNT_USER, 1) AS PUCHASED_RATIO
FROM (
    SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR , TO_CHAR(SALES_DATE, 'MM') AS MONTH, COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
    
    (SELECT COUNT(DISTINCT USER_ID) AS USERNUM
    FROM USER_INFO 
    WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
    ) AS COUNT_USER

    FROM ONLINE_SALE
    WHERE USER_ID IN (

                        SELECT USER_ID
                        FROM USER_INFO 
                        WHERE TO_CHAR(JOINED, 'YYYY') = '2021'
                        )
    GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM')
)
ORDER BY YEAR, MONTH