SELECT A.PRODUCT_ID, A.PRODUCT_NAME, (A.PRICE*B.AMOUNT) AS TOTAL_SALES
FROM
(
SELECT PRODUCT_ID, PRODUCT_NAME, PRICE
FROM FOOD_PRODUCT 
) A
JOIN
(
SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
FROM FOOD_ORDER 
WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY PRODUCT_ID
) B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE, B.AMOUNT
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;