SELECT FLAVOR
FROM
(
    SELECT A.FLAVOR, DENSE_RANK() OVER(ORDER BY (A.TOTAL_ORDER + B.JULY_TOTAL) DESC)  AS RANKTOTAL
    FROM
    (
        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF    
    ) A
    JOIN
    (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
        FROM JULY
        GROUP BY FLAVOR
    ) B
    ON A.FLAVOR = B.FLAVOR
)
WHERE RANKTOTAL <= 3