SELECT A.ANIMAL_ID, A.NAME
FROM
(SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_OUTS) A -- 입양
JOIN
(SELECT ANIMAL_ID, DATETIME FROM ANIMAL_INS)  B -- 보호
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.DATETIME < B.DATETIME
ORDER BY B.DATETIME ASC