SELECT BOOK_ID, AUTHOR_NAME, to_char(PUBLISHED_DATE, 'yyyy-mm-dd') as PUBLISHED_DATE
FROM 
(
    SELECT *
    FROM BOOK
    WHERE CATEGORY = '경제'
) A
JOIN
(
    SELECT *
    FROM AUTHOR
) B
ON A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY PUBLISHED_DATE ASC;