SELECT FLAVOR 
FROM 
( 
    SELECT F.FLAVOR, (F.TOTAL_ORDER + J.TOTAL_ORDER2) AS TOTAL_ORDER
    FROM FIRST_HALF F,
        (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER2 FROM JULY
        GROUP BY FLAVOR
        ) J
    WHERE J.FLAVOR = F.FLAVOR
    ORDER BY TOTAL_ORDER DESC
)WHERE ROWNUM <= 3